In [ ]:
import pandas as pd
import numpy as np
init_seed = 42
np.random.seed(init_seed) 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import classification_report, confusion_matrix,precision_recall_curve, roc_curve, auc, roc_auc_score
from sklearn import datasets, ensemble
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder, label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.inspection import permutation_importance
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier

from econml.dr import DRLearner

import xgboost as xgb
print(xgb.__version__)
from xgboost import XGBClassifier

2.1.3

In [ ]:
############import datafile################################################
file_path1 = 'data/Label_data_n_258.csv'
data = pd.read_csv(file_path1)#, engine='openpyxl'
data

,VEC_HEA,Omega_HEA,Hmix_HEA,Electroneg_HEA,DeltaSize_HEA,Smix_HEA,Al+Cr,Cr/Al,Refractory_sum,NiCoCrAlFe_sum,...,T(C),Pdflist,Entry,Oxidation Time,Oxidation Weight Gain (mg/cm2),cluster,kn,n,kn_err,n_err
0,5.90000,0.0,-2.520000,0.048000,0.042854,2.702740,90.000000,0.0,10.000000,90.000000,...,1100,1,1,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN
1,5.90000,0.0,-2.520000,0.048000,0.042854,2.702740,90.000000,0.0,10.000000,90.000000,...,1100,1,1,18.000000,4.120390,0.0,NaN,NaN,NaN,NaN
2,5.90000,0.0,-2.520000,0.048000,0.042854,2.702740,90.000000,0.0,10.000000,90.000000,...,1100,1,1,36.000000,5.824330,0.0,0.946893,2.002759,0.000000,0.000000
3,5.90000,0.0,-2.520000,0.048000,0.042854,2.702740,90.000000,0.0,10.000000,90.000000,...,1100,1,1,54.000000,7.010000,0.0,1.060853,2.075546,0.074484,0.038911
4,5.90000,0.0,-2.520000,0.048000,0.042854,2.702740,90.000000,0.0,10.000000,90.000000,...,1100,1,1,72.000000,7.527830,0.0,1.629717,2.333774,0.548810,0.178756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32755,5.41736,0.0,-26.549443,0.096331,0.074681,8.008781,56.694406,0.0,28.347203,56.694406,...,1200,786,5057,30.038109,21.229542,1.0,508.994565,3.153408,0.000000,0.000000
32756,5.41736,0.0,-26.549443,0.096331,0.074681,8.008781,56.694406,0.0,28.347203,56.694406,...,1200,786,5057,45.057164,25.642753,1.0,121.763157,2.663350,81.926711,0.216908
32757,5.41736,0.0,-26.549443,0.096331,0.074681,8.008781,56.694406,0.0,28.347203,56.694406,...,1200,786,5057,60.076218,29.871108,0.0,53.820536,2.391688,30.976757,0.178783
32758,5.41736,0.0,-26.549443,0.096331,0.074681,8.008781,56.694406,0.0,28.347203,56.694406,...,1200,786,5057,75.095273,34.652044,0.0,25.260857,2.147013,14.179034,0.168374
32759,5.41736,0.0,-26.549443,0.096331,0.074681,8.008781,56.694406,0.0,28.347203,56.694406,...,1200,786,5057,90.114327,38.699669,0.0,16.289163,2.008895,7.613756,0.136170

In [3]:
###########check features################
fnum = 258
# features = data.columns[0:246].tolist()
features = data.columns[0:fnum].tolist()+['Oxidation Time']
print(f'features are:{features}')
##########check data#######################
# data[features]
print(f'data contain Nan: {data[features].isna().any().any()}')
print(f'data contain inf: {np.isinf(np.isinf(data.iloc[:,:252].values).any()).any()}')

features are:['VEC_HEA', 'Omega_HEA', 'Hmix_HEA', 'Electroneg_HEA', 'DeltaSize_HEA', 'Smix_HEA', 'Al+Cr', 'Cr/Al', 'Refractory_sum', 'NiCoCrAlFe_sum', 'ECVF', 'WAPBR_ZrO2', 'WAPBR_TiO2', 'WAPBR_Ta2O5', 'WAPBR_Nb2O5', 'WAPBR_WO3', 'WAPBR_MoO3', 'WAPBR_V2O5', 'WAPBR_Fe2O3', 'WAPBR_Al2O3', 'WAPBR_Co3O4', 'WAPBR_Cr2O3', 'WAPBR_NiO', 'WAPBR', 'WAOR_ZrO2', 'WAOR_TiO2', 'WAOR_Ta2O5', 'WAOR_Nb2O5', 'WAOR_WO3', 'WAOR_MoO3', 'WAOR_V2O5', 'WAOR_Fe2O3', 'WAOR_Al2O3', 'WAOR_Co3O4', 'WAOR_Cr2O3', 'WAOR_NiO', 'WAOR', 'WOMR_ZrO2', 'WOMR_TiO2', 'WOMR_Ta2O5', 'WOMR_Nb2O5', 'WOMR_WO3', 'WOMR_MoO3', 'WOMR_V2O5', 'WOMR_Fe2O3', 'WOMR_Al2O3', 'WOMR_Co3O4', 'WOMR_Cr2O3', 'WOMR_NiO', 'WOMR', 'WSD_Ni', 'WSD_Co', 'WSD_Cr', 'WSD_Al', 'WSD_Fe', 'WSD_Nb', 'WSD_Ta', 'WSD_Ti', 'WSD_Zr', 'WSD_Mo', 'WSD_W', 'WSD_V', 'WSD', 'WID_V', 'WID_W', 'WID_Mo', 'WID_Zr', 'WID_Ti', 'WID_Ta', 'WID_Nb', 'WID_Fe', 'WID_Al', 'WID_Cr', 'WID_Co', 'WID_Ni', 'WID', 'WODS_Zr', 'WODS_Ti', 'WODS_Ta', 'WODS_Nb', 'WODS_W', 'WODS_Mo', 'WODS_V', 'WODS_Fe', 'WODS_Al', 'WODS_Co', 'WODS_Cr', 'WODS_Ni', 'WODS', 'WOSS_Zr', 'WOSS_Ti', 'WOSS_Ta', 'WOSS_Nb', 'WOSS_W', 'WOSS_Mo', 'WOSS_V', 'WOSS_Fe', 'WOSS_Al', 'WOSS_Co', 'WOSS_Cr', 'WOSS_Ni', 'WOSS', 'WVOC_NiO', 'WVOC_Cr2O3', 'WVOC_Co3O4', 'WVOC_Al2O3', 'WVOC_Fe2O3', 'WVOC_V2O5', 'WVOC_MoO3', 'WVOC_WO3', 'WVOC_Nb2O5', 'WVOC_Ta2O5', 'WVOC_TiO2', 'WVOC_ZrO2', 'WVOC', 'WOMS_ZrO2', 'WOMS_TiO2', 'WOMS_Ta2O5', 'WOMS_Nb2O5', 'WOMS_WO3', 'WOMS_MoO3', 'WOMS_V2O5', 'WOMS_Fe2O3', 'WOMS_Al2O3', 'WOMS_Co3O4', 'WOMS_Cr2O3', 'WOMS_NiO', 'WOMS', 'WSS', 'WSS_TiO2', 'WSS_Cr2O3', 'WSS_Al2O3', 'MaxGi', 'MinGi', 'MaxG', 'MinG', 'SOGF', 'WAKP_NiO', 'WAKP_Fe2O3', 'WAKP_Co3O4', 'WAKP_Al2O3', 'WAKP_Cr2O3', 'WAKP_WO3', 'WAKP_V2O5', 'WAKP_TiO2', 'WAKP_Ta2O5', 'WAKP_Nb2O5', 'WAKP_MoO3', 'WAKP_ZrO2', 'WAKP', 'WAPO_NiO', 'WAPO_Fe2O3', 'WAPO_Co3O4', 'WAPO_Al2O3', 'WAPO_Cr2O3', 'WAPO_WO3', 'WAPO_V2O5', 'WAPO_TiO2', 'WAPO_Ta2O5', 'WAPO_Nb2O5', 'WAPO_MoO3', 'WAPO_ZrO2', 'WAPO', 'WOGF', 'OGf_NiO', 'OGf_Fe3O4', 'OGf_Fe2O3', 'OGf_FeO', 'OGf_Co3O4', 'OGf_CoO', 'OGf_Al2O3', 'OGf_Cr2O3', 'OGf_CrO3', 'OGf_WO3', 'OGf_WO2', 'OGf_V2O5', 'OGf_V2O3', 'OGf_VO2', 'OGf_TiO2', 'OGf_Ta2O5', 'OGf_TaO2', 'OGf_Nb2O5', 'OGf_NbO2', 'OGf_MoO3', 'OGf_MoO2', 'OGf_ZrO2', 'OGf_ZrO', 'Cr', 'Ta', 'Nb', 'Mo', 'Si', 'Ti', 'La', 'Fe', 'MgO', 'B', 'W', 'Co', 'Al', 'Mn', 'C', 'Ni', 'Re', 'V', 'Zr', 'Hf', 'S', 'P', 'Gd', 'Cu', 'Y', 'Ce', 'O', 'Mg', 'Y2O3', 'Cr2O3', 'SiO2', 'Al2O3', 'TiO2', 'La2O3', 'Eu2O3', 'CeO2', 'Sm2O3', 'Gd2O3', 'ZrO2', 'Ta2O5', 'Yb2O3', 'Dy2O3', 'Lu2O3', 'Er2O3', 'Ho2O3', 'Tb2O3', 'Th', 'N', 'Ru', 'Sm', 'Yb', 'Sc', 'Nd', 'Dy', 'Pt', 'Na', 'Sn', 'Ge', 'Lu', 'H', 'Pd', 'Ca', 'Ag', 'Au', 'pO2(mmHg)', 'cyc', 'dis', 'iso', 'N.1', 'Y.1', 'T(C)', 'Oxidation Time']
data contain Nan: False
data contain inf: False

In [4]:
#################################################################################
# Standardize the features
#################################################################################
# Columns to exclude
exclude_columns = ['cyc', 'dis', 'iso','N.1','Y.1']
##################Boolean to int################################# 
data[exclude_columns] = data[exclude_columns].astype(int)
########################################################################
# Remove elements in arrayA from arrayB
Numerical = list(set(features) - set(exclude_columns))
scaler = StandardScaler()
scaler.fit(data[Numerical])
###############################################################################################
data[Numerical] = scaler.transform(data[Numerical])
data

,VEC_HEA,Omega_HEA,Hmix_HEA,Electroneg_HEA,DeltaSize_HEA,Smix_HEA,Al+Cr,Cr/Al,Refractory_sum,NiCoCrAlFe_sum,...,T(C),Pdflist,Entry,Oxidation Time,Oxidation Weight Gain (mg/cm2),cluster,kn,n,kn_err,n_err
0,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.761761,1,1,-0.259887,0.000000,0.0,NaN,NaN,NaN,NaN
1,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.761761,1,1,-0.227408,4.120390,0.0,NaN,NaN,NaN,NaN
2,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.761761,1,1,-0.194930,5.824330,0.0,0.946893,2.002759,0.000000,0.000000
3,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.761761,1,1,-0.162451,7.010000,0.0,1.060853,2.075546,0.074484,0.038911
4,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.761761,1,1,-0.129972,7.527830,0.0,1.629717,2.333774,0.548810,0.178756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32755,-0.754256,0.0,-1.278191,-0.310916,0.860840,-0.057465,2.064229,-0.102796,0.039716,-0.295791,...,1.318022,786,5057,-0.205687,21.229542,1.0,508.994565,3.153408,0.000000,0.000000
32756,-0.754256,0.0,-1.278191,-0.310916,0.860840,-0.057465,2.064229,-0.102796,0.039716,-0.295791,...,1.318022,786,5057,-0.178587,25.642753,1.0,121.763157,2.663350,81.926711,0.216908
32757,-0.754256,0.0,-1.278191,-0.310916,0.860840,-0.057465,2.064229,-0.102796,0.039716,-0.295791,...,1.318022,786,5057,-0.151487,29.871108,0.0,53.820536,2.391688,30.976757,0.178783
32758,-0.754256,0.0,-1.278191,-0.310916,0.860840,-0.057465,2.064229,-0.102796,0.039716,-0.295791,...,1.318022,786,5057,-0.124387,34.652044,0.0,25.260857,2.147013,14.179034,0.168374
32759,-0.754256,0.0,-1.278191,-0.310916,0.860840,-0.057465,2.064229,-0.102796,0.039716,-0.295791,...,1.318022,786,5057,-0.097287,38.699669,0.0,16.289163,2.008895,7.613756,0.136170

In [5]:
#################################SMOTE#######################################
tem = data.copy()
tem = tem[~tem['cluster'].isna()]
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X_smote, T_smote = sm.fit_resample(tem[features], tem['cluster'])
X_smote

,VEC_HEA,Omega_HEA,Hmix_HEA,Electroneg_HEA,DeltaSize_HEA,Smix_HEA,Al+Cr,Cr/Al,Refractory_sum,NiCoCrAlFe_sum,...,Ag,Au,pO2(mmHg),cyc,dis,iso,N.1,Y.1,T(C),Oxidation Time
0,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.0,-0.018595,-0.115233,1,0,0,1,0,0.761761,-0.259887
1,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.0,-0.018595,-0.115233,1,0,0,1,0,0.761761,-0.227408
2,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.0,-0.018595,-0.115233,1,0,0,1,0,0.761761,-0.194930
3,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.0,-0.018595,-0.115233,1,0,0,1,0,0.761761,-0.162451
4,-0.485437,0.0,0.929520,-1.155079,-0.142336,-1.543374,4.116745,-0.102796,-0.488432,0.592892,...,0.0,-0.018595,-0.115233,1,0,0,1,0,0.761761,-0.129972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53293,1.209938,0.0,0.653920,0.063198,-1.024149,-0.879811,0.165890,-0.102796,-0.776296,0.843892,...,0.0,-0.018595,-0.115233,0,1,0,0,1,0.205501,0.982847
53294,0.917600,0.0,-0.295237,0.433166,0.294578,0.340846,-0.181108,-0.097693,-0.551450,0.651305,...,0.0,-0.018595,-0.115233,0,1,0,1,0,1.318022,-0.164665
53295,0.998945,0.0,0.484098,0.280599,-0.281310,0.065052,0.243454,0.041810,-0.616189,0.674814,...,0.0,-0.018595,-0.115233,0,1,0,0,1,0.761761,0.532275
53296,0.795608,0.0,1.009415,-0.459847,-0.329197,0.336184,-0.320382,-0.102796,-0.776296,0.406113,...,0.0,-0.018595,-0.115233,0,0,1,0,1,0.205501,-0.135648
53297,0.766033,0.0,0.647330,0.061322,0.310335,-1.131569,-1.144332,-0.102796,-0.586306,0.577683,...,0.0,-0.018595,-0.115233,1,0,0,1,0,-0.907019,-0.257475

In [ ]:
############import datafile################################################
corr_matrix = pd.read_csv("data/pearson_correlation.csv", index_col=0)#, engine='openpyxl'
shap_df = pd.read_csv("data/total SHAP importance_RF100n211.csv")#, engine='openpyxl'
rankindex = 'avg SHAP Importance' #avg SHAP Importance   Geometric Mean SHAP Importance
shap_df = shap_df.sort_values(by=rankindex, ascending=False)
shap_df

,Unnamed: 0,Feature,avg SHAP Importance,Geometric Mean SHAP Importance,Rank SHAP Importance
258,258,Oxidation Time,0.065442,0.063729,257.0
256,256,Y.1,0.035239,0.017271,209.0
252,252,cyc,0.031084,0.017827,223.0
108,108,WVOC_MoO3,0.023279,0.016221,233.5
254,254,iso,0.018096,0.013191,222.0
...,...,...,...,...,...
102,102,WVOC_NiO,0.000000,0.000000,8.0
113,113,WVOC_ZrO2,0.000000,0.000000,16.5
112,112,WVOC_TiO2,0.000000,0.000000,4.0
105,105,WVOC_Al2O3,0.000000,0.000000,8.0
1,1,Omega_HEA,0.000000,0.000000,4.0

In [7]:
####################Identify Highly Correlated Features (Threshold = 0.85)######################################
corr_matrix_abs = corr_matrix.abs()

# Identify highly correlated feature pairs (|correlation| > 0.85)
high_corr_pairs = set()
for i in range(len(corr_matrix_abs.columns)):
    for j in range(i + 1, len(corr_matrix_abs.columns)):
        if corr_matrix_abs.iloc[i, j] > 0.85:
            high_corr_pairs.add((corr_matrix_abs.columns[i], corr_matrix_abs.columns[j],corr_matrix_abs.iloc[i, j]))

print("Highly correlated pairs:", high_corr_pairs)
# Convert to DataFrame
high_corr_df = pd.DataFrame(high_corr_pairs, columns=["Feature1", "Feature2", "Correlation"])

Highly correlated pairs: {('WODS_Cr', 'WOSS_Cr', 0.8669642472097573), ('WOSS_Cr', 'OGf_CrO3', 0.8756626222532107), ('WSD_Ni', 'WOSS_Ni', 0.8615579537710494), ('WSD_Al', 'Al', 0.9492877225436652), ('WOSS_Ni', 'Ni', 0.8597287601353802), ('WAPBR_Cr2O3', 'WOMS_Cr2O3', 0.9582226652237584), ('WAOR', 'MaxG', 0.9324292579798134), ('WODS_Ni', 'WAPO', 0.8659357243371589), ('WAPBR_Al2O3', 'WSD_Al', 0.9499222710076296), ('WOMR_Al2O3', 'WODS_Al', 0.9478572341282866), ('VEC_HEA', 'WSS_Al2O3', 0.906414728211196), ('WSD', 'OGf_CrO3', 0.9583402036324687), ('WOMR_Cr2O3', 'WOSS_Cr', 0.8956243534000071), ('WSD', 'OGf_Cr2O3', 0.9592523740129172), ('WAPBR_NiO', 'WOMR_NiO', 0.8947580567697437), ('WOSS_Cr', 'WVOC_Cr2O3', 0.8568651721236834), ('WAPBR_Cr2O3', 'OGf_Cr2O3', 0.9663295662878632), ('WSD_Ni', 'WOMS_NiO', 0.8852275514634745), ('WOMS_NiO', 'OGf_NiO', 0.8935523588137991), ('WODS_Ni', 'WAPO_NiO', 0.8931639032539066), ('WODS_Al', 'OGf_Al2O3', 0.94674962659138), ('OGf_NiO', 'Ni', 0.8891184788807623), ('WOMR_Cr2O3', 'WVOC_Cr2O3', 0.9068613554082215), ('WOMR_Al2O3', 'OGf_Al2O3', 0.9486577360693118), ('WODS_Cr', 'WAPO_Cr2O3', 0.8748727416489478), ('WODS_Al', 'Al', 0.9484870096328842), ('WVOC_Cr2O3', 'WOMS_Cr2O3', 0.8768336985285317), ('WSD_Al', 'WOMS_Al2O3', 0.9448763965094096), ('OGf_Al2O3', 'Al', 0.9484801661931834), ('WAPO_NiO', 'WAPO', 0.8684150109465075), ('WSD_Al', 'WODS_Al', 0.9472102814540204), ('Refractory_sum', 'NiCoCrAlFe_sum', 0.8536613360440505), ('WOMR_NiO', 'WOMS_NiO', 0.8841517010145646), ('WAPBR_Cr2O3', 'Cr', 0.96897723746389), ('WSD', 'WOMS_Cr2O3', 0.9512521082281278), ('WOMR_Cr2O3', 'WSD_Cr', 0.9686013383364678), ('WOSS_Cr', 'WOMS_Cr2O3', 0.8568399151250399), ('WSD_Cr', 'OGf_Cr2O3', 0.9652453822924516), ('ECVF', 'MaxG', 0.9503250536928372), ('WAPBR_Al2O3', 'Al', 0.9501993772221066), ('WOMS_NiO', 'Ni', 0.8855153073833921), ('WSD', 'WVOC_Cr2O3', 0.9019221950388538), ('WSD_Cr', 'OGf_CrO3', 0.9647353464200736), ('WOMR_NiO', 'WSD_Ni', 0.8952393917269724), ('WOMR_NiO', 'OGf_NiO', 0.8894014021084977), ('WVOC_Cr2O3', 'OGf_Cr2O3', 0.8937657285359897), ('WAPBR_Cr2O3', 'WVOC_Cr2O3', 0.90691889938987), ('WSD_Cr', 'WSD', 0.9618814924287832), ('WAPBR_Cr2O3', 'WSD', 0.9620017606624722), ('OGf_Cr2O3', 'OGf_CrO3', 0.9686755041267114), ('WSD_Cr', 'WOSS_Cr', 0.8968871286824069), ('WAPBR_Cr2O3', 'WOSS_Cr', 0.8952929174330075), ('WAPBR_NiO', 'WSD_Ni', 0.8947567055961614), ('ECVF', 'WAOR', 0.982103350743982), ('WOMR_Cr2O3', 'WSD', 0.9617120038613568), ('WAPBR_NiO', 'WOMS_NiO', 0.8846861360060312), ('WOSS_Ni', 'WAPO', 0.8600417642735104), ('WODS_Ni', 'WOSS_Ni', 0.8902950340803314), ('WOMR_Al2O3', 'WOMS_Al2O3', 0.945183799220558), ('WOMS_Al2O3', 'OGf_Al2O3', 0.947544611519908), ('WODS_Al', 'WOMS_Al2O3', 0.9435865495467776), ('WAPBR_NiO', 'OGf_NiO', 0.890196565423749), ('OGf_CrO3', 'Cr', 0.9655747554050336), ('WSD', 'WOSS_Cr', 0.8887066437707184), ('WAPBR_Al2O3', 'WOMR_Al2O3', 0.948689176430141), ('WOSS_Cr', 'Cr', 0.8952489625675017), ('WSD_Ni', 'WSS', 0.8534989586664741), ('WOMR_NiO', 'WSS', 0.8551376695688423), ('WAPBR_NiO', 'WSS', 0.8538212629514788), ('WSS', 'Ni', 0.8524071757714311), ('WSS', 'WSS_Al2O3', 0.8973286509311906), ('WVOC_Cr2O3', 'OGf_CrO3', 0.8927311312801267), ('WOMS_Cr2O3', 'OGf_Cr2O3', 0.9657927680072016), ('WOMR_Cr2O3', 'WOMS_Cr2O3', 0.9586394687060912), ('WSD_Cr', 'Cr', 0.9680965040339428), ('WOMS_Cr2O3', 'OGf_CrO3', 0.9659903171263194), ('WAPBR_Cr2O3', 'WOMR_Cr2O3', 0.9685749568960168), ('WSS', 'OGf_NiO', 0.8531620361201374), ('WSD', 'Cr', 0.9616238115622864), ('OGf_Cr2O3', 'Cr', 0.9662074916758562), ('WAPBR_Al2O3', 'WODS_Al', 0.947984942332518), ('WSD_Ni', 'Ni', 0.8934808368874634), ('WOMR_Cr2O3', 'OGf_Cr2O3', 0.9658663789801504), ('WSD_Cr', 'WOMS_Cr2O3', 0.9572872104275272), ('WAPBR_NiO', 'Ni', 0.8951500977637001), ('WOMR_Cr2O3', 'Cr', 0.9681960737267856), ('WOMR_Al2O3', 'WSD_Al', 0.9496682173087366), ('WSD_Ni', 'OGf_NiO', 0.8895064696392697), ('WSD_Al', 'OGf_Al2O3', 0.9490821542595604), ('WVOC_Cr2O3', 'Cr', 0.9064933410227544), ('WOMR_NiO', 'WOSS_Ni', 0.860373248553199), ('WOMR_NiO', 'Ni', 0.894881828764796), ('WAPBR_Al2O3', 'WOMS_Al2O3', 0.945027246921939), ('WOMS_Al2O3', 'Al', 0.9459912230945826), ('VEC_HEA', 'WSS', 0.9124373237763498), ('WSD_Cr', 'WVOC_Cr2O3', 0.9084364450378282), ('WAPBR_NiO', 'WOSS_Ni', 0.8610881956666732), ('WOMR_Cr2O3', 'OGf_CrO3', 0.9659443082781982), ('WOMR_Al2O3', 'Al', 0.9501007365261572), ('WOMS_Cr2O3', 'Cr', 0.9582441579679984), ('WAPBR_Cr2O3', 'WSD_Cr', 0.9685565511674554), ('WSS_TiO2', 'WSS_Cr2O3', 0.9573009768990802), ('WOSS_Ni', 'WAPO_NiO', 0.8865512302126083), ('WOSS_Cr', 'OGf_Cr2O3', 0.8786711870281441), ('WAPBR_Al2O3', 'OGf_Al2O3', 0.9481703791895116), ('WAPBR_Cr2O3', 'OGf_CrO3', 0.9649538736377532)}

In [8]:
# Remove the less important feature from each correlated pair
features_to_remove = []
f1shap = []
f2shap = []
for f1, f2, _ in high_corr_pairs:
    f1shap.append(shap_df.loc[shap_df["Feature"] == f1, rankindex].iloc[0])
    f2shap.append(shap_df.loc[shap_df["Feature"] == f2, rankindex].iloc[0])
    if shap_df.loc[shap_df["Feature"] == f1, rankindex].iloc[0] <= shap_df.loc[shap_df["Feature"] == f2, rankindex].iloc[0]:
        features_to_remove.append(f1)
    else:
        features_to_remove.append(f2)
high_corr_df['f1 Weighted SHAP Importance']=f1shap
high_corr_df['f2 Weighted SHAP Importance']=f2shap
high_corr_df['Removed']=features_to_remove
##################################################################
#################Summary Output##################################################################
print("\n🎯 Summary of Process:")
print(f"- Features removed: {set(features_to_remove)}")
print(f"- Remaining features: {list(data.columns)}")

🎯 Summary of Process:
- Features removed: {'WOMR_Al2O3', 'WODS_Al', 'WSS_Al2O3', 'WVOC_Cr2O3', 'WOMR_Cr2O3', 'OGf_Cr2O3', 'Refractory_sum', 'WSD_Cr', 'OGf_CrO3', 'WOSS_Ni', 'WAPO', 'Al', 'WOSS_Cr', 'WODS_Cr', 'WOMS_NiO', 'VEC_HEA', 'WAPBR_Al2O3', 'WSD_Al', 'Cr', 'WAPBR_Cr2O3', 'WOMR_NiO', 'OGf_NiO', 'MaxG', 'WSS_Cr2O3', 'WAPBR_NiO', 'WSD_Ni', 'ECVF', 'OGf_Al2O3', 'WAPO_NiO', 'WOMS_Cr2O3', 'Ni'}
- Remaining features: ['VEC_HEA', 'Omega_HEA', 'Hmix_HEA', 'Electroneg_HEA', 'DeltaSize_HEA', 'Smix_HEA', 'Al+Cr', 'Cr/Al', 'Refractory_sum', 'NiCoCrAlFe_sum', 'ECVF', 'WAPBR_ZrO2', 'WAPBR_TiO2', 'WAPBR_Ta2O5', 'WAPBR_Nb2O5', 'WAPBR_WO3', 'WAPBR_MoO3', 'WAPBR_V2O5', 'WAPBR_Fe2O3', 'WAPBR_Al2O3', 'WAPBR_Co3O4', 'WAPBR_Cr2O3', 'WAPBR_NiO', 'WAPBR', 'WAOR_ZrO2', 'WAOR_TiO2', 'WAOR_Ta2O5', 'WAOR_Nb2O5', 'WAOR_WO3', 'WAOR_MoO3', 'WAOR_V2O5', 'WAOR_Fe2O3', 'WAOR_Al2O3', 'WAOR_Co3O4', 'WAOR_Cr2O3', 'WAOR_NiO', 'WAOR', 'WOMR_ZrO2', 'WOMR_TiO2', 'WOMR_Ta2O5', 'WOMR_Nb2O5', 'WOMR_WO3', 'WOMR_MoO3', 'WOMR_V2O5', 'WOMR_Fe2O3', 'WOMR_Al2O3', 'WOMR_Co3O4', 'WOMR_Cr2O3', 'WOMR_NiO', 'WOMR', 'WSD_Ni', 'WSD_Co', 'WSD_Cr', 'WSD_Al', 'WSD_Fe', 'WSD_Nb', 'WSD_Ta', 'WSD_Ti', 'WSD_Zr', 'WSD_Mo', 'WSD_W', 'WSD_V', 'WSD', 'WID_V', 'WID_W', 'WID_Mo', 'WID_Zr', 'WID_Ti', 'WID_Ta', 'WID_Nb', 'WID_Fe', 'WID_Al', 'WID_Cr', 'WID_Co', 'WID_Ni', 'WID', 'WODS_Zr', 'WODS_Ti', 'WODS_Ta', 'WODS_Nb', 'WODS_W', 'WODS_Mo', 'WODS_V', 'WODS_Fe', 'WODS_Al', 'WODS_Co', 'WODS_Cr', 'WODS_Ni', 'WODS', 'WOSS_Zr', 'WOSS_Ti', 'WOSS_Ta', 'WOSS_Nb', 'WOSS_W', 'WOSS_Mo', 'WOSS_V', 'WOSS_Fe', 'WOSS_Al', 'WOSS_Co', 'WOSS_Cr', 'WOSS_Ni', 'WOSS', 'WVOC_NiO', 'WVOC_Cr2O3', 'WVOC_Co3O4', 'WVOC_Al2O3', 'WVOC_Fe2O3', 'WVOC_V2O5', 'WVOC_MoO3', 'WVOC_WO3', 'WVOC_Nb2O5', 'WVOC_Ta2O5', 'WVOC_TiO2', 'WVOC_ZrO2', 'WVOC', 'WOMS_ZrO2', 'WOMS_TiO2', 'WOMS_Ta2O5', 'WOMS_Nb2O5', 'WOMS_WO3', 'WOMS_MoO3', 'WOMS_V2O5', 'WOMS_Fe2O3', 'WOMS_Al2O3', 'WOMS_Co3O4', 'WOMS_Cr2O3', 'WOMS_NiO', 'WOMS', 'WSS', 'WSS_TiO2', 'WSS_Cr2O3', 'WSS_Al2O3', 'MaxGi', 'MinGi', 'MaxG', 'MinG', 'SOGF', 'WAKP_NiO', 'WAKP_Fe2O3', 'WAKP_Co3O4', 'WAKP_Al2O3', 'WAKP_Cr2O3', 'WAKP_WO3', 'WAKP_V2O5', 'WAKP_TiO2', 'WAKP_Ta2O5', 'WAKP_Nb2O5', 'WAKP_MoO3', 'WAKP_ZrO2', 'WAKP', 'WAPO_NiO', 'WAPO_Fe2O3', 'WAPO_Co3O4', 'WAPO_Al2O3', 'WAPO_Cr2O3', 'WAPO_WO3', 'WAPO_V2O5', 'WAPO_TiO2', 'WAPO_Ta2O5', 'WAPO_Nb2O5', 'WAPO_MoO3', 'WAPO_ZrO2', 'WAPO', 'WOGF', 'OGf_NiO', 'OGf_Fe3O4', 'OGf_Fe2O3', 'OGf_FeO', 'OGf_Co3O4', 'OGf_CoO', 'OGf_Al2O3', 'OGf_Cr2O3', 'OGf_CrO3', 'OGf_WO3', 'OGf_WO2', 'OGf_V2O5', 'OGf_V2O3', 'OGf_VO2', 'OGf_TiO2', 'OGf_Ta2O5', 'OGf_TaO2', 'OGf_Nb2O5', 'OGf_NbO2', 'OGf_MoO3', 'OGf_MoO2', 'OGf_ZrO2', 'OGf_ZrO', 'Cr', 'Ta', 'Nb', 'Mo', 'Si', 'Ti', 'La', 'Fe', 'MgO', 'B', 'W', 'Co', 'Al', 'Mn', 'C', 'Ni', 'Re', 'V', 'Zr', 'Hf', 'S', 'P', 'Gd', 'Cu', 'Y', 'Ce', 'O', 'Mg', 'Y2O3', 'Cr2O3', 'SiO2', 'Al2O3', 'TiO2', 'La2O3', 'Eu2O3', 'CeO2', 'Sm2O3', 'Gd2O3', 'ZrO2', 'Ta2O5', 'Yb2O3', 'Dy2O3', 'Lu2O3', 'Er2O3', 'Ho2O3', 'Tb2O3', 'Th', 'N', 'Ru', 'Sm', 'Yb', 'Sc', 'Nd', 'Dy', 'Pt', 'Na', 'Sn', 'Ge', 'Lu', 'H', 'Pd', 'Ca', 'Ag', 'Au', 'pO2(mmHg)', 'cyc', 'dis', 'iso', 'N.1', 'Y.1', 'T(C)', 'Pdflist', 'Entry', 'Oxidation Time', 'Oxidation Weight Gain (mg/cm2)', 'cluster', 'kn', 'n', 'kn_err', 'n_err']

In [ ]:
# check
shap_df_filtered = shap_df[~shap_df["Feature"].isin(features_to_remove)]
shap_df_filtered[shap_df_filtered['Feature'].str.contains('_Nb', na=False)]

,Unnamed: 0,Feature,avg SHAP Importance,Geometric Mean SHAP Importance,Rank SHAP Importance
55,55,WSD_Nb,0.004771,0.004082,191.0
27,27,WAOR_Nb2O5,0.004421,0.003905,180.0
181,181,OGf_Nb2O5,0.004112,0.003157,168.5
92,92,WOSS_Nb,0.003960,0.003390,168.0
118,118,WOMS_Nb2O5,0.003921,0.003802,168.0
79,79,WODS_Nb,0.003917,0.003678,166.5
40,40,WOMR_Nb2O5,0.003571,0.000000,136.5
182,182,OGf_NbO2,0.003469,0.001521,147.0
69,69,WID_Nb,0.003371,0.003295,157.0
14,14,WAPBR_Nb2O5,0.003330,0.002001,144.0
146,146,WAKP_Nb2O5,0.003216,0.003067,149.0
159,159,WAPO_Nb2O5,0.002052,0.001620,110.0
110,110,WVOC_Nb2O5,0.000710,0.000680,75.5

In [10]:
from sklearn.linear_model import LogisticRegression, RidgeCV,LogisticRegression
from sklearn.linear_model import LassoCV, RidgeCV
from numpy.linalg import cond
import xgboost as xgb
from sklearn.tree import DecisionTreeRegressor

In [ ]:
RANDOM_STATE = 24
def causal_function(T_smote,X_smote,raw_data,features,treatment):
    data_final = raw_data.copy()
# Loop over each treatment type (1, 2, and 3)
    for treat in range(treatment):
        # Prepare data: X (features), y (outcome), and T_binary (binary indicator)
        X = raw_data[features].values#
        y = raw_data['Oxidation Weight Gain (mg/cm2)'].values
        # Create a binary treatment indicator: 1 if treatment equals 'treat', 0 otherwise.
        data_final[f'T_{treat}'] = (raw_data['cluster'] == treat).astype(int)
        T_binary = data_final[f'T_{treat}'].values.astype(int)
       #######define clf model, fit first cause the databse is balenced ##################
        X_smote_copy = X_smote[features].values
        T_smote_copy = (T_smote== treat).astype(int)
        model_clf = xgb.XGBClassifier(random_state=RANDOM_STATE,
            n_estimators=40,max_depth=10,learning_rate=0.5,subsample=0.9,min_child_weight=3)
        model_clf.fit(X_smote_copy, T_smote_copy)  
        #######define reg model##################
        # Specify machine learning models for the two nuisance functions.
        model_reg = ensemble.RandomForestRegressor(random_state=RANDOM_STATE,n_estimators=100, max_depth=None,min_samples_split=2,min_samples_leaf=1,max_features=1)#
        #######define final model##################
        model_final = RidgeCV(alphas=np.logspace(-3, 3, 7))
        # Initialize DRLearner (which expects a binary treatment)
        dr_learner = DRLearner(model_regression=model_reg,
                               model_propensity=model_clf,
                               model_final=model_final,
                               random_state=RANDOM_STATE,
                               cv=5)  # 
        # Fit the DRLearner on the binary treatment indicator.
        dr_learner.fit(y, T_binary, X=X)
        # Estimate the Conditional Average Treatment Effect (CATE) for each individual
        cate = dr_learner.effect(X)
        data_final[f'CATE_T_{treat}'] = cate
        # The average effect for treatment 't' (versus not receiving t) is:
        ate = np.mean(cate)
      
        print(f"Estimated ATE for treatment {treat} (vs. not {treat}): {ate:.3f}")
    return data_final

In [173]:
dfs = {}
##########################initial no feature engineering ###############################
features = data.columns[0:fnum].tolist()+['Oxidation Time']
print(f"The remaining features is: {len(features)}") 

dfs[f'CSVI threadhold:Initial'] = causal_function(T_smote,X_smote,data,features,3)

The remaining features is: 259
Estimated ATE for treatment 0 (vs. not 0): 1.165
Estimated ATE for treatment 1 (vs. not 1): -0.654
Estimated ATE for treatment 2 (vs. not 2): -6.019

In [ ]:
##########################just remove correlate feature keep all CSVI features ###############################
##############################remove hightle corelate features####################################################################################################################################
shap_df_filtered = shap_df[~shap_df["Feature"].isin(features_to_remove)]
##########################################################################################
CSVI_limt = [0,1e-6,5e-6,1e-5,5e-5,1e-4,5e-4,1e-3,5e-3,0.01,0.02,0.03]
for threshold in CSVI_limt:
    print("#############################")
    print(f"The CSVI threadhold is: {threshold}")
##############################remove low CSVI features######################################################################################################
    shap_df_final = shap_df_filtered[shap_df_filtered[rankindex]>=threshold]  
    print("#############################")
    features = shap_df_final['Feature'].tolist()
    print(f"The remaining high CSVI features is: {len(features)}") 
    ####################################################################################################
    plotvalue = len(features)
    plt.figure(figsize=(10, 5))
    plt.plot(shap_df_final["Feature"][:plotvalue], shap_df_final[rankindex][:plotvalue], marker="o", linestyle="-", color="b")
    plt.ylabel("CSVI")
    plt.xticks(rotation=45)  # Rotate x labels if needed
    plt.axhline(y=threshold, color='r', linestyle='--')#, label="y = 10"
    # Show the plot
    plt.show()
    ##########################################################################################
    dfs[f'CSVI threadhold:{threshold}'] = causal_function(T_smote,X_smote,data,features,3)

In [92]:
from sklearn.ensemble import GradientBoostingRegressor
import xgboost as xgb
from sklearn.metrics import make_scorer,r2_score,root_mean_squared_error, mean_squared_error,mean_absolute_error,classification_report, confusion_matrix,precision_recall_curve, roc_curve, auc, roc_auc_score
from sklearn.model_selection import GridSearchCV,KFold, cross_val_score, train_test_split,cross_validate
RANDOM_STATE = None

In [93]:
reg_results = {}
clf_results = {}
features_num = []

In [ ]:
##########################initial no feature engineering ###############################
features = data.columns[0:fnum].tolist()+['Oxidation Time']
features_num.append(len(features))
print(f"The remaining features is: {len(features)}") 
######reg#########reg############reg##############reg#####reg##############reg#########reg############reg##############reg#####reg###########
# Specify machine learning models for the two nuisance functions.
model_reg = ensemble.RandomForestRegressor(random_state=RANDOM_STATE,n_estimators=100, max_depth=None,min_samples_split=2,min_samples_leaf=1,max_features=1)#
######################################################################################################
# Define the scoring metrics
scoring = {
    'RMSE':make_scorer(root_mean_squared_error),
    'MAE': make_scorer(mean_absolute_error),
    'MSE': make_scorer(mean_squared_error),
    'R2': make_scorer(r2_score)
}
# Perform five-fold cross-validation on the training set
kfold = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
cv_results = cross_validate(model_reg, data[features], data['Oxidation Weight Gain (mg/cm2)'], cv=kfold, scoring=scoring)
reg_results[f'CSVI threadhold:Initial'] = cv_results
# # Extract and print the cross-validation results
print("Train CV RMSE Score:", cv_results['test_RMSE'].mean(),'±',cv_results['test_RMSE'].std())
print("Train CV MAE Score:", cv_results['test_MAE'].mean(),'±',cv_results['test_MAE'].std())
print("Train CV MSE Score:", cv_results['test_MSE'].mean(),'±',cv_results['test_MSE'].std())
print("Train CV R2 Score:", cv_results['test_R2'].mean(),'±',cv_results['test_R2'].std())
#######clf############clf#################clf#########################clf#####################clf#############clf###########clf############clf############    
params = {
    'n_estimators': 40,
    'max_depth': 10,
    'learning_rate': 0.5,
    'subsample': 0.9,
    'min_child_weight': 3,}
XGBoost_clf = xgb.XGBClassifier(objective='multi:softmax', num_class=3, eval_metric='mlogloss',**params,random_state=RANDOM_STATE)
# 5-Fold Cross-Validation
kf = KFold(n_splits=5, shuffle=True,random_state=RANDOM_STATE)
# Store reports
all_reports = []
# Cross-validation loop
for train_idx, test_idx in kf.split(X_smote, T_smote):
    X_train, X_test = X_smote[features].iloc[train_idx], X_smote[features].iloc[test_idx]
    y_train, y_test = T_smote.iloc[train_idx], T_smote.iloc[test_idx]

    XGBoost_clf.fit(X_train, y_train)
    y_pred = XGBoost_clf.predict(X_test)

    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    all_reports.append(report)
# Convert to DataFrames and average
# We'll exclude 'accuracy' for now since it's a scalar (not per-class)
report_dfs = [pd.DataFrame(r).T for r in all_reports]

# Align all columns first (in case any class is missing in a fold)
for df in report_dfs:
    for metric in ['precision', 'recall', 'f1-score', 'support']:
        if metric not in df.columns:
            df[metric] = 0
# Stack and average
combined_df = pd.concat(report_dfs).groupby(level=0).mean()
# Add average accuracy separately
accuracy_scores = [r['accuracy'] for r in all_reports]
combined_df.loc['accuracy'] = [np.mean(accuracy_scores), 0, 0, 0]  # pad other columns
# Final averaged classification report
print("\n=== Averaged Classification Report ===")
print(combined_df)
clf_results[f'CSVI threadhold:Initial'] = combined_df

The remaining features is: 259
Train CV RMSE Score: 16.8041016419161 ± 2.446077221809423
Train CV MAE Score: 3.8026638162074393 ± 0.12222266167057663
Train CV MSE Score: 288.36112576690226 ± 84.81128181897392
Train CV R2 Score: 0.8795769423682364 ± 0.027250941904083847

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.866073  0.885390  0.875590   3553.2
1.0            0.879211  0.852565  0.865644   3553.2
2.0            0.988212  0.996115  0.992148   3553.2
accuracy       0.911329  0.000000  0.000000      0.0
macro avg      0.911165  0.911357  0.911127  10659.6
weighted avg   0.911182  0.911329  0.911121  10659.6

In [ ]:
##########################just remove correlate feature keep all CSVI features ###############################
##############################remove hightle corelate features####################################################################################################################################
shap_df_filtered = shap_df[~shap_df["Feature"].isin(features_to_remove)]
##########################################################################################
CSVI_limt = [0,1e-6,5e-6,1e-5,5e-5,1e-4,5e-4,1e-3,5e-3,0.01,0.02,0.03]
for threshold in CSVI_limt:
    print("#############################")
    print(f"The CSVI threadhold is: {threshold}")
##############################remove low CSVI features######################################################################################################
    shap_df_final = shap_df_filtered[shap_df_filtered[rankindex]>=threshold]  
    print("#############################")
    features = shap_df_final['Feature'].tolist()
    print(f"The remaining high CSVI features is: {len(features)}") 
    features_num.append(len(features))
######reg#########reg############reg##############reg#####reg##############reg#########reg############reg##############reg#####reg###########
    model_reg = ensemble.RandomForestRegressor(random_state=RANDOM_STATE,n_estimators=100, max_depth=None,min_samples_split=2,min_samples_leaf=1,max_features=1)#
    ######################################################################################################
    # Define the scoring metrics
    scoring = {
        'RMSE':make_scorer(root_mean_squared_error),
        'MAE': make_scorer(mean_absolute_error),
        'MSE': make_scorer(mean_squared_error),
        'R2': make_scorer(r2_score)
    }
    # Perform five-fold cross-validation on the training set
    kfold = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    cv_results = cross_validate(model_reg, data[features], data['Oxidation Weight Gain (mg/cm2)'], cv=kfold, scoring=scoring)
    reg_results[f'CSVI threadhold:{threshold}'] = cv_results
    # # Extract and print the cross-validation results
    print("Train CV RMSE Score:", cv_results['test_RMSE'].mean(),'±',cv_results['test_RMSE'].std())
    print("Train CV MAE Score:", cv_results['test_MAE'].mean(),'±',cv_results['test_MAE'].std())
    print("Train CV MSE Score:", cv_results['test_MSE'].mean(),'±',cv_results['test_MSE'].std())
    print("Train CV R2 Score:", cv_results['test_R2'].mean(),'±',cv_results['test_R2'].std())
#######clf############clf#################clf#########################clf#####################clf#############clf###########clf############clf############    
    params = {
        'n_estimators': 40,
        'max_depth': 10,
        'learning_rate': 0.5,
        'subsample': 0.9,
        'min_child_weight': 3,}
    XGBoost_clf = xgb.XGBClassifier(objective='multi:softmax', num_class=3, eval_metric='mlogloss',**params,random_state=RANDOM_STATE)
    # 5-Fold Cross-Validation
    kf = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    # Store reports
    all_reports = []
    # Cross-validation loop
    for train_idx, test_idx in kf.split(X_smote, T_smote):
        X_train, X_test = X_smote[features].iloc[train_idx], X_smote[features].iloc[test_idx]
        y_train, y_test = T_smote.iloc[train_idx], T_smote.iloc[test_idx]
    
        XGBoost_clf.fit(X_train, y_train)
        y_pred = XGBoost_clf.predict(X_test)
    
        report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
        all_reports.append(report)
    # Convert to DataFrames and average
    # We'll exclude 'accuracy' for now since it's a scalar (not per-class)
    report_dfs = [pd.DataFrame(r).T for r in all_reports]
    
    # Align all columns first (in case any class is missing in a fold)
    for df in report_dfs:
        for metric in ['precision', 'recall', 'f1-score', 'support']:
            if metric not in df.columns:
                df[metric] = 0
    # Stack and average
    combined_df = pd.concat(report_dfs).groupby(level=0).mean()
    # Add average accuracy separately
    accuracy_scores = [r['accuracy'] for r in all_reports]
    combined_df.loc['accuracy'] = [np.mean(accuracy_scores), 0, 0, 0]  # pad other columns
    # Final averaged classification report
    print("\n=== Averaged Classification Report ===")
    print(combined_df)
    clf_results[f'CSVI threadhold:{threshold}'] = combined_df

#############################
The CSVI threadhold is: 0
#############################
The remaining high CSVI features is: 228
Train CV RMSE Score: 16.71008227137603 ± 2.263472893643365
Train CV MAE Score: 3.7932054413127836 ± 0.2200137823121055
Train CV MSE Score: 284.3501590564138 ± 76.72274266302551
Train CV R2 Score: 0.8810801282454402 ± 0.030908586587514227

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.870754  0.889443  0.879965   3553.2
1.0            0.882806  0.857007  0.869663   3553.2
2.0            0.987595  0.995380  0.991469   3553.2
accuracy       0.913899  0.000000  0.000000      0.0
macro avg      0.913718  0.913943  0.913699  10659.6
weighted avg   0.913777  0.913899  0.913705  10659.6
#############################
The CSVI threadhold is: 1e-06
#############################
The remaining high CSVI features is: 214
Train CV RMSE Score: 18.516374088318127 ± 4.349329507079305
Train CV MAE Score: 3.8800510852720267 ± 0.18191805141172165
Train CV MSE Score: 361.77277653968963 ± 171.48601758152282
Train CV R2 Score: 0.8512954406013996 ± 0.061324308217880465

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.866974  0.885213  0.875978   3553.2
1.0            0.878778  0.851748  0.865022   3553.2
2.0            0.986299  0.995830  0.991040   3553.2
accuracy       0.910916  0.000000  0.000000      0.0
macro avg      0.910684  0.910930  0.910680  10659.6
weighted avg   0.910686  0.910916  0.910674  10659.6
#############################
The CSVI threadhold is: 5e-06
#############################
The remaining high CSVI features is: 209
Train CV RMSE Score: 17.172469778222204 ± 1.8887555933222402
Train CV MAE Score: 3.7836937645104043 ± 0.1774908728237963
Train CV MSE Score: 298.46111597526095 ± 65.26636998530007
Train CV R2 Score: 0.8690396294881955 ± 0.04112580261913358

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.870824  0.891481  0.881019   3553.2
1.0            0.885033  0.857904  0.871237   3553.2
2.0            0.988593  0.995557  0.992061   3553.2
accuracy       0.914969  0.000000  0.000000      0.0
macro avg      0.914817  0.914981  0.914772  10659.6
weighted avg   0.914869  0.914969  0.914793  10659.6
#############################
The CSVI threadhold is: 1e-05
#############################
The remaining high CSVI features is: 206
Train CV RMSE Score: 17.040210489970452 ± 3.39957791065438
Train CV MAE Score: 3.8424107224066804 ± 0.37859137970411527
Train CV MSE Score: 301.92590351310815 ± 117.4699869661817
Train CV R2 Score: 0.8725213339291455 ± 0.04786433312053364

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.867971  0.888824  0.878258   3553.2
1.0            0.882759  0.854945  0.868601   3553.2
2.0            0.988610  0.995887  0.992233   3553.2
accuracy       0.913224  0.000000  0.000000      0.0
macro avg      0.913113  0.913219  0.913031  10659.6
weighted avg   0.913105  0.913224  0.913029  10659.6
#############################
The CSVI threadhold is: 5e-05
#############################
The remaining high CSVI features is: 196
Train CV RMSE Score: 18.150854655978918 ± 2.6751612859650704
Train CV MAE Score: 3.8446405181938736 ± 0.15022165641835114
Train CV MSE Score: 336.61001264839786 ± 105.51248861640681
Train CV R2 Score: 0.8593009239375785 ± 0.03548689378430229

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.868208  0.888351  0.878159   3553.2
1.0            0.881795  0.854194  0.867770   3553.2
2.0            0.987552  0.995551  0.991534   3553.2
accuracy       0.912698  0.000000  0.000000      0.0
macro avg      0.912518  0.912699  0.912488  10659.6
weighted avg   0.912528  0.912698  0.912492  10659.6
#############################
The CSVI threadhold is: 0.0001
#############################
The remaining high CSVI features is: 190
Train CV RMSE Score: 18.25262335659439 ± 4.744455991673733
Train CV MAE Score: 3.837698804511974 ± 0.2432741260688967
Train CV MSE Score: 355.6681220546237 ± 185.53524292728883
Train CV R2 Score: 0.8592281345967088 ± 0.04589581993807333

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.872080  0.895200  0.883478   3553.2
1.0            0.888330  0.857984  0.872881   3553.2
2.0            0.988086  0.995607  0.991832   3553.2
accuracy       0.916282  0.000000  0.000000      0.0
macro avg      0.916165  0.916263  0.916064  10659.6
weighted avg   0.916185  0.916282  0.916082  10659.6
#############################
The CSVI threadhold is: 0.0005
#############################
The remaining high CSVI features is: 179
Train CV RMSE Score: 18.5214140019821 ± 1.5641531181404253
Train CV MAE Score: 3.852481966334608 ± 0.05774017733393135
Train CV MSE Score: 345.4893516098071 ± 58.782879887294115
Train CV R2 Score: 0.8556520149961674 ± 0.015864626445232892

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.867728  0.889368  0.878387   3553.2
1.0            0.883049  0.853953  0.868215   3553.2
2.0            0.987884  0.995614  0.991727   3553.2
accuracy       0.912999  0.000000  0.000000      0.0
macro avg      0.912887  0.912978  0.912776  10659.6
weighted avg   0.912900  0.912999  0.912792  10659.6
#############################
The CSVI threadhold is: 0.001
#############################
The remaining high CSVI features is: 158
Train CV RMSE Score: 17.28988384426226 ± 2.6846642130254703
Train CV MAE Score: 3.836216926406066 ± 0.1711953907909954
Train CV MSE Score: 306.1475052847808 ± 97.42996452545574
Train CV R2 Score: 0.8704589164937543 ± 0.03911886430998507

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.874038  0.893884  0.883831   3553.2
1.0            0.887398  0.860861  0.873905   3553.2
2.0            0.988496  0.995551  0.992010   3553.2
accuracy       0.916770  0.000000  0.000000      0.0
macro avg      0.916644  0.916765  0.916582  10659.6
weighted avg   0.916654  0.916770  0.916589  10659.6
#############################
The CSVI threadhold is: 0.002
#############################
The remaining high CSVI features is: 126
Train CV RMSE Score: 16.774993655160536 ± 1.731696374152396
Train CV MAE Score: 3.7881174617777473 ± 0.1429152533469752
Train CV MSE Score: 284.3991844629289 ± 59.59282347254157
Train CV R2 Score: 0.8687477708168403 ± 0.054725902775289985

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.873747  0.891375  0.882444   3553.2
1.0            0.885376  0.860741  0.872857   3553.2
2.0            0.988089  0.995833  0.991945   3553.2
accuracy       0.915944  0.000000  0.000000      0.0
macro avg      0.915737  0.915983  0.915748  10659.6
weighted avg   0.915802  0.915944  0.915761  10659.6
#############################
The CSVI threadhold is: 0.003
#############################
The remaining high CSVI features is: 99
Train CV RMSE Score: 17.32279572449378 ± 3.6968407036565996
Train CV MAE Score: 3.814257823738335 ± 0.24930337454111737
Train CV MSE Score: 313.7458829007523 ± 133.82725652771703
Train CV R2 Score: 0.8692027186964602 ± 0.05190035974259662

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.875397  0.895289  0.885184   3553.2
1.0            0.889068  0.862586  0.875582   3553.2
2.0            0.988990  0.995834  0.992399   3553.2
accuracy       0.917896  0.000000  0.000000      0.0
macro avg      0.917818  0.917903  0.917722  10659.6
weighted avg   0.917830  0.917896  0.917724  10659.6
#############################
The CSVI threadhold is: 0.004
#############################
The remaining high CSVI features is: 70
Train CV RMSE Score: 17.233206864249407 ± 0.9926008604438881
Train CV MAE Score: 3.7657628667301033 ± 0.15395348324615546
Train CV MSE Score: 297.96867529416687 ± 35.477913374630496
Train CV R2 Score: 0.874545048879844 ± 0.013137214750023897

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.877809  0.899382  0.888458   3553.2
1.0            0.892877  0.864694  0.878551   3553.2
2.0            0.988766  0.995666  0.992203   3553.2
accuracy       0.919922  0.000000  0.000000      0.0
macro avg      0.919817  0.919914  0.919737  10659.6
weighted avg   0.919833  0.919922  0.919749  10659.6
#############################
The CSVI threadhold is: 0.005
#############################
The remaining high CSVI features is: 53
Train CV RMSE Score: 16.99015430204848 ± 3.1884269749995147
Train CV MAE Score: 3.7112680616926403 ± 0.26418887012820186
Train CV MSE Score: 298.83140978232103 ± 118.25519493243398
Train CV R2 Score: 0.87727641175894 ± 0.03328365195221094

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.882184  0.896870  0.889450   3553.2
1.0            0.892235  0.870544  0.881236   3553.2
2.0            0.988431  0.996054  0.992228   3553.2
accuracy       0.921142  0.000000  0.000000      0.0
macro avg      0.920950  0.921156  0.920971  10659.6
weighted avg   0.920974  0.921142  0.920976  10659.6
#############################
The CSVI threadhold is: 0.006
#############################
The remaining high CSVI features is: 41
Train CV RMSE Score: 16.666678759296264 ± 2.5598337433875287
Train CV MAE Score: 3.690288267733444 ± 0.13236744842919626
Train CV MSE Score: 284.3309296593626 ± 87.8471680006954
Train CV R2 Score: 0.8772799390104365 ± 0.04608436124297954

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.885866  0.903752  0.894703   3553.2
1.0            0.899133  0.874466  0.886614   3553.2
2.0            0.989388  0.996564  0.992962   3553.2
accuracy       0.924913  0.000000  0.000000      0.0
macro avg      0.924796  0.924928  0.924760  10659.6
weighted avg   0.924806  0.924913  0.924758  10659.6
#############################
The CSVI threadhold is: 0.007
#############################
The remaining high CSVI features is: 32
Train CV RMSE Score: 15.79234295270525 ± 2.2003424682696235
Train CV MAE Score: 3.6453879346615308 ± 0.21014605790080032
Train CV MSE Score: 254.23960291353006 ± 69.61750588216698
Train CV R2 Score: 0.8897277613938657 ± 0.03634623696806923

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.881023  0.898884  0.889860   3553.2
1.0            0.892803  0.869131  0.880800   3553.2
2.0            0.988884  0.995055  0.991958   3553.2
accuracy       0.921029  0.000000  0.000000      0.0
macro avg      0.920903  0.921023  0.920873  10659.6
weighted avg   0.920917  0.921029  0.920883  10659.6
#############################
The CSVI threadhold is: 0.008
#############################
The remaining high CSVI features is: 25
Train CV RMSE Score: 14.875662410921771 ± 2.5311564174266863
Train CV MAE Score: 3.617403007390455 ± 0.2610280502068153
Train CV MSE Score: 227.69208497319124 ± 77.37246898841404
Train CV R2 Score: 0.9034613570667467 ± 0.03404238354215896

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.876583  0.897349  0.886838   3553.2
1.0            0.891651  0.863147  0.877159   3553.2
2.0            0.987494  0.995665  0.991562   3553.2
accuracy       0.918721  0.000000  0.000000      0.0
macro avg      0.918576  0.918720  0.918520  10659.6
weighted avg   0.918582  0.918721  0.918523  10659.6
#############################
The CSVI threadhold is: 0.009
#############################
The remaining high CSVI features is: 14
Train CV RMSE Score: 13.848996679237928 ± 0.6688677970495503
Train CV MAE Score: 3.573093814869181 ± 0.1275843345474151
Train CV MSE Score: 192.24209315147309 ± 18.80877529006953
Train CV R2 Score: 0.9193227564537644 ± 0.008272301930167907

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.865917  0.876622  0.871219   3553.2
1.0            0.871308  0.853227  0.862149   3553.2
2.0            0.985816  0.994089  0.989934   3553.2
accuracy       0.907970  0.000000  0.000000      0.0
macro avg      0.907680  0.907979  0.907767  10659.6
weighted avg   0.907697  0.907970  0.907771  10659.6
#############################
The CSVI threadhold is: 0.01
#############################
The remaining high CSVI features is: 10
Train CV RMSE Score: 18.094914306799488 ± 2.0220691017511965
Train CV MAE Score: 4.136743226394326 ± 0.11354717684246957
Train CV MSE Score: 331.5146872226738 ± 70.2326099072158
Train CV R2 Score: 0.8612695157335704 ± 0.02950302960561188

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.834041  0.844011  0.838972   3553.2
1.0            0.836082  0.820530  0.828194   3553.2
2.0            0.982073  0.988790  0.985416   3553.2
accuracy       0.884423  0.000000  0.000000      0.0
macro avg      0.884065  0.884444  0.884194  10659.6
weighted avg   0.884155  0.884423  0.884228  10659.6
#############################
The CSVI threadhold is: 0.02
#############################
The remaining high CSVI features is: 4
Train CV RMSE Score: 40.588322273836766 ± 2.9155730867006517
Train CV MAE Score: 13.961174765989716 ± 0.2291258193212729
Train CV MSE Score: 1655.912471428727 ± 248.86168413711465
Train CV R2 Score: 0.30883543154518206 ± 0.025613108032226998

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.548188  0.572289  0.559955   3553.2
1.0            0.578796  0.594611  0.586553   3553.2
2.0            0.875028  0.812608  0.842651   3553.2
accuracy       0.659837  0.000000  0.000000      0.0
macro avg      0.667337  0.659836  0.663053  10659.6
weighted avg   0.667395  0.659837  0.663084  10659.6
#############################
The CSVI threadhold is: 0.03
#############################
The remaining high CSVI features is: 3
Train CV RMSE Score: 46.1405762500382 ± 2.736741447753554
Train CV MAE Score: 16.38013504883417 ± 0.3839948245532171
Train CV MSE Score: 2136.4425304374417 ± 255.28638943102942
Train CV R2 Score: 0.09054474215365102 ± 0.12553476681053163

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.451712  0.410680  0.430118   3553.2
1.0            0.514293  0.573294  0.542133   3553.2
2.0            0.690901  0.673537  0.681898   3553.2
accuracy       0.552535  0.000000  0.000000      0.0
macro avg      0.552302  0.552504  0.551383  10659.6
weighted avg   0.552310  0.552535  0.551403  10659.6
#############################
The CSVI threadhold is: 0.04
#############################
The remaining high CSVI features is: 1
Train CV RMSE Score: 49.39382134403191 ± 1.6750205422004507
Train CV MAE Score: 17.607106024795932 ± 0.3185334120207139
Train CV MSE Score: 2442.5552807829363 ± 164.16568231535118
Train CV R2 Score: -0.025157023012558268 ± 0.04043289143448679

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.370653  0.143186  0.206505   3553.2
1.0            0.493804  0.600270  0.541722   3553.2
2.0            0.498183  0.696430  0.580783   3553.2
accuracy       0.479943  0.000000  0.000000      0.0
macro avg      0.454213  0.479962  0.443004  10659.6
weighted avg   0.454244  0.479943  0.443023  10659.6
#############################
The CSVI threadhold is: 0.05
#############################
The remaining high CSVI features is: 1
Train CV RMSE Score: 50.36442419939514 ± 2.7160665057537328
Train CV MAE Score: 17.726832733524546 ± 0.5289697363198597
Train CV MSE Score: 2543.9522422002965 ± 276.6704723094819
Train CV R2 Score: -0.06841596405781389 ± 0.08881090709187459

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.375457  0.147062  0.210814   3553.2
1.0            0.490706  0.597874  0.538982   3553.2
2.0            0.502151  0.698140  0.584055   3553.2
accuracy       0.481069  0.000000  0.000000      0.0
macro avg      0.456105  0.481025  0.444617  10659.6
weighted avg   0.456139  0.481069  0.444658  10659.6
#############################
The CSVI threadhold is: 0.06
#############################
The remaining high CSVI features is: 1
Train CV RMSE Score: 49.558463028620665 ± 3.5458697787084064
Train CV MAE Score: 17.61611925125994 ± 0.6318745860787961
Train CV MSE Score: 2468.6144502467187 ± 356.79987470929973
Train CV R2 Score: -0.05303459845028491 ± 0.10461060987554997

=== Averaged Classification Report ===
              precision    recall  f1-score  support
0.0            0.370943  0.156851  0.220217   3553.2
1.0            0.489111  0.592525  0.535768   3553.2
2.0            0.500185  0.682433  0.577225   3553.2
accuracy       0.477297  0.000000  0.000000      0.0
macro avg      0.453413  0.477270  0.444404  10659.6
weighted avg   0.453428  0.477297  0.444426  10659.6

In [11]:
import pickle

# with open('Step5/dataframes_regresult_RF100n211_navg.pkl', 'wb') as f:
#     pickle.dump(reg_results, f)
# with open('Step5/dataframes_clfresult_XG_RF100n211_navg.pkl', 'wb') as f:
#     pickle.dump(clf_results, f)
# with open('Step5/features_nu_RF100n211_navg.pkl', 'wb') as f:
#     pickle.dump(features_num, f)
with open('Step5/dataframes_regresult_RF100n211_24avg.pkl', 'rb') as f:
    reg_results = pickle.load(f)
with open('Step5/dataframes_clfresult_XG_RF100n211_24avg.pkl', 'rb') as f:
    clf_results = pickle.load(f)
with open('Step5/features_nu_RF100n211_24avg.pkl', 'rb') as f:
    features_num = pickle.load(f)

In [ ]:
plotname = [0,1e-6,5e-6,1e-5,5e-5,1e-4,5e-4,1e-3,5e-3,0.01,0.02,0.03]
RMSE=[]
MAE=[]
MSE=[]
for threshold in plotname:
    RMSE.append(reg_results[f'CSVI threadhold:{threshold}']['test_RMSE'].mean())
    MAE.append(reg_results[f'CSVI threadhold:{threshold}']['test_MAE'].mean())
    MSE.append(reg_results[f'CSVI threadhold:{threshold}']['test_MSE'].mean())

fig, axes = plt.subplots(1, 3, figsize=(12, 5))
axes[0].plot(plotname, RMSE, linestyle='-', marker='o', color='b', label='RMSE')
axes[0].set_xlabel('CSVI threshold')
axes[0].set_ylabel('Performance')
# plt.grid(True)
axes[0].legend()
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=45)

axes[1].plot(plotname, MAE, linestyle='-', marker='*', color='r', label='MAE')
axes[1].set_xlabel('CSVI threshold')
axes[1].set_ylabel('Performance')
# plt.grid(True)
axes[1].legend()
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=45)

axes[2].plot(plotname, MSE, linestyle='-', marker='^', color='g', label='MSE')
axes[2].set_xlabel('CSVI threshold')
axes[2].set_ylabel('Performance')
# plt.grid(True)
axes[2].legend()
axes[2].set_xticklabels(axes[1].get_xticklabels(), rotation=45)

plt.tight_layout()
plt.show()

# Minimum value and index in A
min_A = np.min(RMSE)
idx_A = np.argmin(RMSE)

# Minimum value and index in B
min_B = np.min(MSE)
idx_B = np.argmin(MSE)

# Minimum value and index in C
min_C = np.min(MAE)
idx_C = np.argmin(MAE)

# Print results
print(f"RMSE: min = {min_A},CSVI threshold = {plotname[idx_A]}, number of features = {features_num[idx_A]}")
print(f"MSE: min = {min_B},CSVI threshold = {plotname[idx_B]}, number of features = {features_num[idx_B]}")
print(f"MASE: min = {min_C},CSVI threshold = {plotname[idx_C]}, number of features = {features_num[idx_C]}")

In [4]:
fig, ax1 = plt.subplots()

# Plot on left y-axis
line1, = ax1.plot(plotname, RMSE, linestyle='-', marker='o', color='b', label='RMSE')
line2, = ax1.plot(plotname, MAE, linestyle='-', marker='*', color='r', label='MAE')
ax1.set_ylabel('Performance (RMSE & MAE)')

# Create right y-axis
ax2 = ax1.twinx()
line3, = ax2.plot(plotname, MSE, linestyle='-', marker='^', color='g', label='MSE')
ax2.set_ylabel('MSE')

# Combine legends
lines = [line1, line2, line3]
labels = [line.get_label() for line in lines]
ax1.legend(lines, labels, loc='upper left')
ax1.set_xticklabels(ax1.get_xticklabels(), rotation=45)
ax1.set_xlabel('CSVI threshold')
plt.tight_layout()
plt.savefig(f"plot/Step5_causal_reg.png", dpi=800)  # You can change the filename and dpi
plt.show()

NameError: name 'plt' is not defined

In [5]:
T0_precision=[]
T0_recall=[]
T0_f1=[]
T1_precision=[]
T1_recall=[]
T1_f1=[]
T2_precision=[]
T2_recall=[]
T2_f1=[]

for threshold in plotname:
    T0_precision.append(clf_results[f'CSVI threadhold:{threshold}']['precision'].iloc[0])
    T0_recall.append(clf_results[f'CSVI threadhold:{threshold}']['recall'].iloc[0])
    T0_f1.append(clf_results[f'CSVI threadhold:{threshold}']['f1-score'].iloc[0])
    T1_precision.append(clf_results[f'CSVI threadhold:{threshold}']['precision'].iloc[1])
    T1_recall.append(clf_results[f'CSVI threadhold:{threshold}']['recall'].iloc[1])
    T1_f1.append(clf_results[f'CSVI threadhold:{threshold}']['f1-score'].iloc[1])
    T2_precision.append(clf_results[f'CSVI threadhold:{threshold}']['precision'].iloc[2])
    T2_recall.append(clf_results[f'CSVI threadhold:{threshold}']['recall'].iloc[2])
    T2_f1.append(clf_results[f'CSVI threadhold:{threshold}']['f1-score'].iloc[2])
    
fig, axes = plt.subplots(1, 3, figsize=(12, 5))
axes[0].plot(plotname, T0_precision, linestyle='-', marker='^', color='g', label='precision')
axes[0].plot(plotname, T0_recall, linestyle='-', marker='o', color='b', label='recall')
axes[0].plot(plotname, T0_f1, linestyle='-', marker='*', color='r', label='f1')
axes[0].set_xlabel('CSVI threshold')
axes[0].set_ylabel('Performance')
axes[0].set_title('PL')
axes[0].legend()
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=45)

axes[1].plot(plotname, T1_precision, linestyle='-', marker='^', color='g', label='precision')
axes[1].plot(plotname, T1_recall, linestyle='-', marker='o', color='b', label='recall')
axes[1].plot(plotname, T1_f1, linestyle='-', marker='*', color='r', label='f1')
axes[1].set_xlabel('CSVI threshold')
axes[1].set_ylabel('Performance')
axes[1].set_title('NPL')
axes[1].legend()
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=45)

axes[2].plot(plotname, T2_precision, linestyle='-', marker='^', color='g', label='precision')
axes[2].plot(plotname, T2_recall, linestyle='-', marker='o', color='b', label='recall')
axes[2].plot(plotname, T2_f1, linestyle='-', marker='*', color='r', label='f1')
axes[2].set_xlabel('CSVI threshold')
axes[2].set_ylabel('Performance')
axes[2].set_title('WL')
axes[2].legend()
axes[2].set_xticklabels(axes[2].get_xticklabels(), rotation=45)
plt.tight_layout()
plt.savefig(f"plot/Step5_causal_clf.png", dpi=800)  # You can change the filename and dpi
plt.show()

# Minimum value and index in A
min_A = np.max(T0_precision)
idx_A = np.argmax(T0_precision)
# Minimum value and index in B
min_B = np.max(T0_recall)
idx_B = np.argmax(T0_recall)
# Minimum value and index in C
min_C = np.max(T0_f1)
idx_C = np.argmax(T0_f1)
# Print results
print(f"T0_precision: max = {min_A},CSVI threshold = {plotname[idx_A]}, number of features = {features_num[idx_A]}")
print(f"T0_recall: max = {min_B},CSVI threshold = {plotname[idx_B]}, number of features = {features_num[idx_B]}")
print(f"T0_f1: max = {min_C},CSVI threshold = {plotname[idx_C]}, number of features = {features_num[idx_C]}")

# Minimum value and index in A
min_A = np.max(T1_precision)
idx_A = np.argmax(T1_precision)
# Minimum value and index in B
min_B = np.max(T1_recall)
idx_B = np.argmax(T1_recall)
# Minimum value and index in C
min_C = np.max(T1_f1)
idx_C = np.argmax(T1_f1)
# Print results
print(f"T1_precision: max = {min_A},CSVI threshold = {plotname[idx_A]}, number of features = {features_num[idx_A]}")
print(f"T1_recall: max = {min_B},CSVI threshold = {plotname[idx_B]}, number of features = {features_num[idx_B]}")
print(f"T1_f1: max = {min_C},CSVI threshold = {plotname[idx_C]}, number of features = {features_num[idx_C]}")

# Minimum value and index in A
min_A = np.max(T2_precision)
idx_A = np.argmax(T2_precision)
# Minimum value and index in B
min_B = np.max(T2_recall)
idx_B = np.argmax(T2_recall)
# Minimum value and index in C
min_C = np.max(T2_f1)
idx_C = np.argmax(T2_f1)
# Print results
print(f"T2_precision: max = {min_A},CSVI threshold = {plotname[idx_A]}, number of features = {features_num[idx_A]}")
print(f"T2_recall: max = {min_B},CSVI threshold = {plotname[idx_B]}, number of features = {features_num[idx_B]}")
print(f"T2_f1: max = {min_C},CSVI threshold = {plotname[idx_C]}, number of features = {features_num[idx_C]}")

NameError: name 'plotname' is not defined